// Mutaciones de Proyectos Taller (ver test-taller.js): sacar cada esc() de los
// renders y romper cada regla de a una (29/09/2026, con el diseño nuevo y el
// diagrama de actividades).
const path = require('path')
const { correrMutaciones } = require('./mutar')

correrMutaciones({
  suite: path.join(__dirname, 'test-taller.js'),
  original: path.join(__dirname, '..', 'modulos', 'taller.html'),
  funciones: ['htmlTarjetaProyecto', 'htmlVentaTarjeta', 'kv', 'htmlCosto', 'htmlAvisoLista', 'htmlLista', 'htmlChipEstado',
    'htmlFichaCabecera', 'htmlFichaDatos', 'htmlFichaPlata', 'htmlResumenCelu', 'htmlTabGastos', 'htmlTabHoras', 'htmlTabNotas',
    'htmlGrillaArchivos', 'htmlTabArchivos', 'htmlFicha', 'htmlModalVenta', 'htmlModalHoras', 'htmlModalAnular', 'htmlValorHora',
    'htmlBarraG', 'htmlFilasOperario', 'htmlFilasProyecto', 'htmlAvisoDiagrama', 'htmlPanelActividad', 'htmlTarjetaMia',
    'htmlMisActividades', 'htmlModalHorasTarea', 'htmlModalAvance', 'htmlDiagrama'],
  // Lo que sale de un FORMATO propio (fechas, importes, horas, porcentajes) o
  // de una CONSTANTE del código no tiene caracteres escapables: sacarle el
  // esc() no cambia ninguna salida posible. El texto de la base y de la
  // persona (y los errores de la base) sí se miden: esos no van acá.
  equivalentes: [
    ["esc(importe(c, moneda))", "importe(): \"$ \" + un número formateado, o \"—\""],
    ["esc(importe(pr, moneda))", "importe(): \"$ \" + un número formateado, o \"—\""],
    ["esc(pasado ? `se pasó ${importe((c ?? 0) - pr, moneda)}` : porcentaje(av))", "un importe o un porcentaje formateados"],
    ["esc(rotuloKv(rotulo))", "kv() recibe rótulos constantes del código (y \"Horas · N h\", formateado)"],
    ["esc(sub)", "las notas de kv() / del grupo del diagrama se arman con constantes, fechas y números"],
    ["esc(banda)", "bandaDe(): una clave de ETIQUETA_ESTADO o \"atrasado\"/\"presupuestado\", constantes"],
    ["esc(con ? textoVacio(filtros) : 'Todavía no hay proyectos')", "textoVacio(): palabras de PLURAL_ESTADO / ETIQUETA_CATEGORIA, constantes"],
    ["esc(con ? 'Probá con otro estado o sacá los filtros.' : 'Cuando se cargue el primer proyecto del Taller, aparece acá.')", "dos textos constantes"],
    ["esc(textoBotonHora(ctx.valorHora))", "\"Valor de la hora\" + un importe formateado"],
    ["esc(ETIQUETA_CATEGORIA[r.categoria] || 'Sin categoría')", "la etiqueta de ETIQUETA_CATEGORIA (constante) o \"Sin categoría\""],
    ["esc(fechaCorta(r.fecha_entrega_prometida))", "fechaCorta(): dd/mm/aaaa armado con dígitos, o \"—\""],
    ["esc(fechaDiaMes(g.fecha))", "fechaDiaMes(): dd/mm armado con dígitos, o \"—\""],
    ["esc(importe(g.importe, g.moneda || r.moneda || 'ARS'))", "importe(): el prefijo sale de una comparación (US$ o $), no de la moneda cruda"],
    ["esc(String(lista.length))", "un número"],
    ["esc(importe(r.gastado, r.moneda || 'ARS'))", "importe(): \"$ \" + un número formateado, o \"—\""],
    ["esc(fechaDiaMes(h.fecha))", "fechaDiaMes(): dd/mm armado con dígitos, o \"—\""],
    ["esc(horasTexto(h.horas))", "horasTexto(): un número formateado + \" h\", o \"—\""],
    ["esc(c.texto)", "costoDeHoras(): un importe formateado, \"sin valor\" o \"—\""],
    ["esc(cantidadHoras(total))", "un número formateado"],
    ["esc(costoTotal)", "un importe formateado o \"—\""],
    ["esc(momentoCorto(n.fecha))", "momentoCorto(): dd/mm hh:mm de Intl, o \"—\""],
    ["esc(a.tipo === 'foto' ? 'foto' : extensionDe(a.nombre))", "extensionDe(): solo [A-Z0-9] de hasta 5 letras, o \"archivo\""],
    ["esc(ETIQUETA_TIPO[a.tipo] || 'Otro')", "la etiqueta de ETIQUETA_TIPO (constante) o \"Otro\""],
    ["esc(v)", "claves de listas constantes del código (tipos de archivo, de factura, rangos)"],
    ["esc(t)", "etiquetas de listas constantes del código"],
    ["esc(String(n))", "un número"],
    ["esc(titulo)", "títulos constantes (\"Facturar al cliente\" / \"Cargar a la fábrica\") o armados con números"],
    ["esc(pistaImporte(m, r))", "un porcentaje formateado o un texto constante"],
    ["esc(res.linea2)", "resumenVenta(): textos constantes con importes formateados"],
    ["esc(textoConfirmar(m, r))", "\"Confirmar\" + un importe formateado"],
    ["esc(hoyArgentina())", "hoyArgentina(): AAAA-MM-DD de Intl"],
    ["esc(importe(vigente.valor))", "importe(): \"$ \" + un número formateado, o \"—\""],
    ["esc(fechaCorta(vigente.vigente_desde))", "fechaCorta(): dd/mm/aaaa armado con dígitos, o \"—\""],
    ["esc(fechaCorta(v.vigente_desde))", "fechaCorta(): dd/mm/aaaa armado con dígitos, o \"—\""],
    ["esc(importe(v.valor))", "importe(): \"$ \" + un número formateado, o \"—\""],
    ["esc(hoy)", "hoyArgentina(): AAAA-MM-DD de Intl"],
    ["esc(textoNotaHora(hoy))", "un texto constante con una fecha dd/mm"],
    ["esc(clases)", "clases CSS armadas con literales del código"],
    ["esc(estilo)", "grid-column con números y los colores oklch de colorProyecto() (números)"],
    ["esc(ctx.cols)", "columnasCss(): \"170px minmax(0,1fr) …\", números y literales"],
    ["esc(String(L))", "un número (carriles)"],
    ["esc(colorPersona(f.nombre))", "colorPersona(): un color armado con números"],
    ["esc(textoSubPersona(f, ctx.dias))", "\"N h de M h\" o \"N cosas el dd\": números y días constantes"],
    ["esc(col.t)", "colorProyecto(): un oklch armado con números de una paleta constante"],
    ["esc(col.c)", "colorProyecto(): un oklch armado con números de una paleta constante"],
    ["esc(String(diasAtraso(p.fecha_entrega_prometida, ctx.hoy)))", "un número"],
    ["esc(cantidadHoras(h))", "un número formateado"],
    ["esc(p.desde || '')", "una fecha de la columna date fecha_inicio (o la de hoy)"],
    ["esc(p.hasta || '')", "una fecha calculada con sumarDias() (AAAA-MM-DD)"],
    ["esc(DIA_LARGO[diaSemana(choque.dia)])", "un día de DIA_LARGO, constante"],
    ["esc(String(choque.dia).slice(8, 10))", "dos dígitos de una fecha date"],
    ["esc(porcentaje(av))", "porcentaje(): un número formateado o \"—\""],
    ["esc(String(av))", "avanceDe(): un número entre 0 y 100"],
    ["esc(String(DIA_LARGO[w] || '').toUpperCase())", "un día de DIA_LARGO, constante"],
    ["esc(fechaDiaMes(ctx.hoy))", "fechaDiaMes(): dd/mm armado con dígitos"],
    ["esc(String(v))", "los avances rápidos 0, 25, 50, 75 y 100, constantes"],
    ["esc(String(minimo))", "un número (ancho mínimo del lienzo)"],
  ].map(([expr, motivo]) => ({ expr, motivo })),
  manuales: [
    // ── La plata: sin precios, nada de venta ──
    { nombre: 'sin precios se muestra la venta en la ficha', de: "      if (!ctx.precios) {\n        return h + '<div class=\"tl-nota-permiso\">", a: "      if (false) {\n        return h + '<div class=\"tl-nota-permiso\">" },
    { nombre: 'sin precios la tarjeta muestra la venta', de: '(ctx.precios ? htmlVentaTarjeta(', a: '(true ? htmlVentaTarjeta(' },
    { nombre: 'sin precios la cabecera pierde "+ Cargar horas"', de: "      if (ctx.precios) {\n        botones += htmlBotonVenta(r, ctx)", a: "      if (true) {\n        botones += htmlBotonVenta(r, ctx)" },
    { nombre: 'el precio de venta viaja sin permiso', de: "if (precios) claves.push('precio_venta')", a: "claves.push('precio_venta')" },
    { nombre: 'se manda todo, no solo lo que cambió', de: "if (nuevo ? norm(a) === '' : norm(a) === norm(o)) continue", a: "if (nuevo && norm(a) === '') continue" },
    { nombre: 'nunca falta el valor de la hora', de: 'return numero(r?.horas) > 0 && (numero(r?.costo_horas) ?? 0) === 0', a: 'return false' },
    { nombre: 'un importe ausente sale como $ 0', de: "      const n = numero(v)\n      if (n === null) return '—'\n      const signo", a: "      const n = numero(v) ?? 0\n      const signo" },
    { nombre: 'nunca dice "se pasó"', de: 'const pasado = (c ?? 0) > pr', a: 'const pasado = false' },
    { nombre: 'la barra de costo pasa del 100 % de ancho', de: 'const ancho = Math.max(0, Math.min(100, avance))', a: 'const ancho = avance' },
    { nombre: 'una carga de horas sin valor ese día sale en $ 0', de: "if (!v) return { texto: 'sin valor', mal: true }", a: 'if (!v) return { texto: importe(0), mal: false }' },
    { nombre: 'el botón del valor de la hora solo con precios', de: "document.getElementById('tl-acciones-extra').innerHTML =\n", a: "document.getElementById('tl-acciones-extra').innerHTML = !puedePrecios() ? '' :\n" },
    { nombre: 'el valor de la hora se puede cambiar sin precios', de: "      if (precios) {\n        h += '<div class=\"tl-fila-campos\">'", a: "      if (true) {\n        h += '<div class=\"tl-fila-campos\">'" },
    { nombre: 'el valor vigente toma uno futuro', de: '.filter(v => v.vigente_desde <= fecha)', a: '' },
    // ── Facturar / cargar a la fábrica ──
    { nombre: 'confirmar sin permiso de precios llama a la base', de: 'if (m.enviando || !puedePrecios() || !f) return', a: 'if (m.enviando || !f) return' },
    { nombre: 'abrir facturar sin permiso', de: 'if (!r || !puedePrecios()) return', a: 'if (!r) return' },
    { nombre: 'facturar y cargar a la fábrica cruzados', de: "const rpc = m.tipo === 'facturar' ? 'facturar_proyecto' : 'cargar_proyecto_a_fabrica'", a: "const rpc = m.tipo === 'facturar' ? 'cargar_proyecto_a_fabrica' : 'facturar_proyecto'" },
    { nombre: 'sin importe igual se manda', de: "if (m.importe === null || m.importe === undefined || !(m.importe > 0)) return 'Poné el importe.'", a: 'void 0' },
    { nombre: 'el concepto viaja sin limpiar', de: 'p_importe: m.importe, p_concepto: limpio(m.concepto)', a: 'p_importe: m.importe, p_concepto: m.concepto' },
    { nombre: 'sin cliente, facturar habilitado', de: "data-accion=\"facturar\"${r.cliente ? '' : ' disabled title=\"Elegí el cliente en Datos\"'}", a: 'data-accion="facturar"' },
    { nombre: '"Saldo final" no pone lo que falta', de: "      if (clase === 'saldo') {\n        const falta = resumenVenta({ ...m, importe: null }, r).falta\n        if (falta !== null && falta > 0) m.importe = falta\n      }\n", a: '' },
    { nombre: 'cambiar el tipo pisa el concepto escrito', de: 'if (!limpio(m.concepto) || Object.values(etiquetas).includes(limpio(m.concepto))) m.concepto = etiquetas[clase]', a: 'm.concepto = etiquetas[clase]' },
    // ── Horas ──
    { nombre: 'horas: más de 24 pasa', de: "      if (p.horas > 24) return 'Las horas van de 0 a 24.'\n", a: '' },
    { nombre: 'horas: a futuro pasa', de: "if (p.fecha > hoyArgentina()) return 'No se pueden cargar horas a futuro.'", a: 'void 0' },
    { nombre: 'horas: la tarea sin limpiar', de: 'p_tarea: limpio(m.tarea) || null', a: 'p_tarea: m.tarea || null' },
    { nombre: 'horas: se abre la ventana sin cargar', de: "      if (!f?.r || !puedeCargar()) return\n      abrirModal({ tipo: 'horas'", a: "      if (!f?.r) return\n      abrirModal({ tipo: 'horas'" },
    { nombre: 'anular horas llama a otra RPC', de: "supabase.rpc('anular_horas_proyecto', { p_horas_id: m.horasId })", a: "supabase.rpc('anular_horas_proyecto', { p_horas_id: m.tareaId })" },
    // ── La lista y la barra de unidad ──
    { nombre: 'la barra: el Taller no muestra todo', de: '      if (!unidadId || unidadId === estado.tallerId) return true\n      const nombre = estado.unidades.get(unidadId)?.nombre\n      return p.destino', a: '      if (!unidadId) return true\n      const nombre = estado.unidades.get(unidadId)?.nombre\n      return p.destino' },
    { nombre: 'la barra: otra fábrica muestra todo', de: "return p.destino === 'interno' && !!nombre && p.fabrica_destino === nombre", a: 'return true' },
    { nombre: '"Atrasados" incluye los cerrados', de: "if (filtro === 'atrasados') return !!p.atrasado && !CERRADOS.has(p.estado)", a: "if (filtro === 'atrasados') return !!p.atrasado" },
    { nombre: 'el vacío no ofrece sacar los filtros', de: "(con ? '<button type=\"button\" class=\"tl-btn tl-btn--fantasma\" data-accion=\"sacar-filtros\">Sacar los filtros</button>' : '')", a: "''" },
    // ── Personas, fábricas, archivos, links ──
    { nombre: 'las tablets entran como personas', de: "p.activo !== false && p.tipo !== 'sistema' && p.tipo !== 'empresa'", a: "p.activo !== false && p.tipo !== 'empresa'" },
    { nombre: 'la fábrica de pruebas entra como personas', de: 'return sinPersonasDePrueba(reales, fabrica).sort(', a: 'return reales.sort(' },
    { nombre: 'el Taller es fábrica destino', de: '.filter(u => u.id !== estado.tallerId)', a: '' },
    { nombre: 'el nombre de archivo conserva barras', de: ".replace(/[^A-Za-z0-9._-]+/g, '-')", a: '' },
    { nombre: 'hoy en UTC', de: "new Intl.DateTimeFormat('en-CA', { timeZone: ZONA_AR, year: 'numeric'", a: "new Intl.DateTimeFormat('en-CA', { timeZone: 'UTC', year: 'numeric'" },
    { nombre: 'el link directo acepta cualquier cosa', de: "return /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i.test(id || '') ? id : null", a: 'return id' },
    { nombre: 'las iniciales de un nombre solo: una letra', de: "if (p.length === 1) return p[0].slice(0, 2).toLocaleUpperCase('es')", a: 'void 0' },
    // ── El diagrama ──
    { nombre: 'el diagrama muestra los domingos', de: 'if (d && diaSemana(d) !== 0) out.push(d)', a: 'if (d) out.push(d)' },
    { nombre: 'el día tiene 10 horas', de: 'const HORAS_DIA = 8', a: 'const HORAS_DIA = 10' },
    { nombre: 'una atrasada no se corre a hoy', de: 'if (esAtrasada(t, hoy) && iv.fin < hoy) return {', a: 'if (false) return {' },
    { nombre: 'los carriles no se abren', de: 'if (l < 0) { l = fines.length; fines.push(it.b) } else fines[l] = it.b', a: 'if (l < 0) { l = 0; fines[0] = it.b } else fines[l] = it.b' },
    { nombre: 'sin horas estimadas no suma', de: 'numero(t.horas_estimadas) ?? HORAS_DIA * total', a: 'numero(t.horas_estimadas) ?? 0' },
    { nombre: 'una actividad hecha choca', de: '        if (avanceDe(t) >= 100) continue\n        const iv = intervaloTarea(t)', a: '        const iv = intervaloTarea(t)' },
    { nombre: 'la burbuja no cuenta los choques', de: 'burbuja: atrasadas.length + choques.length', a: 'burbuja: atrasadas.length' },
    { nombre: 'el aviso dice "2 cosas" en vez de "dos"', de: "const NUMERO_PALABRA = { 2: 'dos', 3: 'tres', 4: 'cuatro' }", a: 'const NUMERO_PALABRA = {}' },
    { nombre: 'vos no vas primero', de: '(x.id === yo ? -1 : 0) - (y.id === yo ? -1 : 0) || ', a: '' },
    { nombre: 'el diagrama muestra la fábrica de pruebas', de: 'const lista = sinPersonasDePrueba([...filas.values()], fabrica, f => f.id)', a: 'const lista = [...filas.values()]' },
    { nombre: 'las horas disponibles cuentan 5 días', de: 'HORAS_DIA * dias.length', a: 'HORAS_DIA * 5' },
    { nombre: 'el sábado ocupa lo mismo', de: "diaSemana(d) === 6 ? 'minmax(0,0.6fr)' : 'minmax(0,1fr)'", a: "'minmax(0,1fr)'" },
    { nombre: 'solo cargar: ve a todos en el diagrama', de: 'if (soloMias()) personas = personas.filter(p => p.id === estado.miEmpleadoId)', a: 'void 0' },
    { nombre: 'solo cargar: pide todas las actividades', de: 'if (soloMias()) params.p_empleado_id = estado.miEmpleadoId', a: 'void 0' },
    { nombre: 'tareas_taller con p_desde (se pierden las atrasadas)', de: 'const params = { p_hasta: dias[dias.length - 1] }', a: 'const params = { p_desde: dias[0], p_hasta: dias[dias.length - 1] }' },
    { nombre: 'null de tareas_taller no es sin permiso', de: "else if (data === null) { d.error = 'No tenés permiso para ver el diagrama.'; d.tareas = [] }", a: '' },
    { nombre: '"+ Actividad" sin gestionar', de: "(ctx.gestionar ? '<button type=\"button\" class=\"tl-btn tl-btn--primario\" data-accion=\"act-nueva\">", a: "(true ? '<button type=\"button\" class=\"tl-btn tl-btn--primario\" data-accion=\"act-nueva\">" },
    { nombre: 'el borde para estirar sin gestionar', de: "(ctx.gestionar ? '<span class=\"tl-barra-g__borde\"", a: "(true ? '<span class=\"tl-barra-g__borde\"" },
    { nombre: 'abrir el panel sin gestionar', de: 'if (!t || !puedeGestionar()) { estado.diag.sel = id; pintarDiagrama(); return }', a: 'if (!t) { estado.diag.sel = id; pintarDiagrama(); return }' },
    { nombre: 'crear actividad sin gestionar', de: "      if (!puedeGestionar()) return\n      const hoy = hoyArgentina()\n      estado.diag.sel = null", a: "      const hoy = hoyArgentina()\n      estado.diag.sel = null" },
    { nombre: 'arrastrar sin gestionar', de: 'if (!arrastre || !arrastre.puede) return', a: 'if (!arrastre) return' },
    { nombre: 'mover manda también el fin', de: ': { fecha_inicio: dias[a.na] }', a: ': { fecha_inicio: dias[a.na], fecha_fin: dias[a.nb] }' },
    { nombre: 'sacar la persona no manda personas vacío', de: 'out.personas = actual.persona ? [actual.persona] : []', a: 'out.personas = [actual.persona]' },
    { nombre: 'la actividad manda todo, no solo lo que cambió', de: "if (antes ? norm(actual[k]) === norm(antes[k]) : norm(actual[k]) === '') continue", a: "if (!antes && norm(actual[k]) === '') continue" },
    { nombre: 'guardar sin cambios llama a la base', de: '        if (p.id && !Object.keys(datos).length) { cerrarPanel(); return }\n', a: '' },
    { nombre: 'eliminar no es "cancelada"', de: "p_estado: 'cancelada'", a: "p_estado: 'hecha'" },
    { nombre: 'faltaActividad no pide el nombre', de: "if (limpio(p.titulo).length < 2) return 'Poné el nombre de la actividad.'", a: 'void 0' },
    { nombre: 'faltaActividad deja el fin antes del inicio', de: "if (p.hasta < p.desde) return 'La fecha de fin no puede ser anterior a la de inicio.'", a: 'void 0' },
    { nombre: 'el avance no se redondea', de: 'p_avance_pct: Math.round(av)', a: 'p_avance_pct: av' },
    { nombre: 'el celular sin botones de editar ni facturar', de: "((ctx.gestionar || ctx.precios) ? '<div class=\"tl-acciones\">'", a: "(false ? '<div class=\"tl-acciones\">'" },
    { nombre: 'el celular factura sin precios', de: "      if (!ctx.precios) return ''\n      return r.destino === 'interno'", a: "      return r.destino === 'interno'" },
    { nombre: 'la ficha no le pasa el contexto al resumen del celular', de: 'htmlResumenCelu(r, ctx) + htmlFichaDatos', a: 'htmlResumenCelu(r) + htmlFichaDatos' },
    { nombre: 'el avance pasa de 100', de: 'if (av === null || av < 0 || av > 100)', a: 'if (av === null || av < 0)' },
    { nombre: 'la nota de las horas sin limpiar', de: 'p_nota: limpio(m.nota) || null', a: 'p_nota: m.nota || null' },
    { nombre: 'mis horas sin cargar', de: "        if (!t || !puedeCargar()) return\n        if (accion === 'mia-horas')", a: "        if (!t) return\n        if (accion === 'mia-horas')" },
    { nombre: 'mis tarjetas con botones sin cargar', de: '(enHoy && ctx.cargar\n', a: '(enHoy\n' },
  ],
})
